# Generated by Django 4.0.2 on 2022-04-22 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_lister'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='desc',
            new_name='description',
        ),
    ]
