# Generated by Django 4.0.2 on 2022-04-23 16:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_rename_desc_listing_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='move_in',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='move_out',
        ),
        migrations.AddField(
            model_name='listing',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='listing',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
